# starship.toml
# Santtu "MFG38" Pesonen

[battery]
disabled = true

[cmd_duration]
disabled = true

[directory]
format = '[$path]($style) '
style = 'bold green'
truncation_length = 3
truncation_symbol = '.../'
truncate_to_repo = false

[git_status]
style = 'bold yellow'

[username]
show_always = true
format = '[$user]($style): '
style_user = 'bold white'
style_root = 'bold green'

